/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edd.proyecto;

/**
 *
 * @author pedro
 */

// Clase de la Interfaz

public class InicioInterfaz extends javax.swing.JFrame {
    Grafos newgrafo;
    
    /**
     * Creates new form InicioInterfaz
     */
    
    /**
     * Método para presentar la Interfaz 
     */
    
    public InicioInterfaz() {
        initComponents();
        this.newgrafo = new Grafos(7);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        InputArista = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        InsertarCity1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        InsertarCity2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Distance = new javax.swing.JTextField();
        DeleteCity2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        InputDelete = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowGrafo = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        Show = new javax.swing.JButton();
        InsertArista = new javax.swing.JButton();
        DeleteArista = new javax.swing.JButton();
        DeleteVertice = new javax.swing.JButton();
        DeleteCity1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel2.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 50, 40));

        jLabel1.setText("Ingre el valor que desea:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 160, -1));

        InputArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAristaActionPerformed(evt);
            }
        });
        jPanel2.add(InputArista, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 150, 30));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel2.setText("Unimet Ant");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 150, 50));

        jLabel3.setText("Que desea realizar?");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, 30));

        jLabel4.setText("Insertar");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 80, -1));

        jLabel5.setText("Insertar Aristas");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, 20));

        jLabel6.setText("3.-Eliminar Arista");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 100, 10));

        jLabel7.setText("4.-Eliminar Vertice");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        jLabel8.setText("5.-Imprimir");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 70, -1));

        jLabel9.setText("Ingrese una ciudad: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        InsertarCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarCity1ActionPerformed(evt);
            }
        });
        jPanel2.add(InsertarCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 240, -1));

        jLabel10.setText("Ingrese otra ciudad: ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        InsertarCity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarCity2ActionPerformed(evt);
            }
        });
        jPanel2.add(InsertarCity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 230, -1));

        jLabel11.setText("Ingrese una ciudad: ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel12.setText("Ingrese la distancia: ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 120, 20));

        Distance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistanceActionPerformed(evt);
            }
        });
        jPanel2.add(Distance, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 240, -1));

        DeleteCity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCity2ActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteCity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 280, -1));

        jLabel13.setText("Ingrese otra ciudad:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        jLabel14.setText("Ingrese para eliminar: ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        InputDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(InputDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 220, -1));

        ShowGrafo.setColumns(20);
        ShowGrafo.setRows(5);
        jScrollPane1.setViewportView(ShowGrafo);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 340, 200));

        jButton2.setText("Insertar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, 20));

        Show.setText("Show");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });
        jPanel2.add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, 70, 20));

        InsertArista.setText("Insertar");
        InsertArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertAristaActionPerformed(evt);
            }
        });
        jPanel2.add(InsertArista, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, 20));

        DeleteArista.setText("Delete");
        DeleteArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAristaActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteArista, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 70, 20));

        DeleteVertice.setText("Delete");
        DeleteVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteVerticeActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteVertice, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 70, 20));

        DeleteCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCity1ActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 280, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método para Cerrar la Interfaz
     */
    
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * Método para Ingresar una Arista / Camino
     */
    
    private void InputAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAristaActionPerformed
        
    }//GEN-LAST:event_InputAristaActionPerformed

    /**
     * Método para Ingresar una Primera Ciudad
     */
    
    private void InsertarCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarCity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertarCity1ActionPerformed

    /**
     * Método para Ingresar una Segunda Ciudad
     */
    
    private void InsertarCity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarCity2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertarCity2ActionPerformed

    /**
     * Método para Ingresar una Segunda Ciudad
     */
    
    private void DeleteCity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCity2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteCity2ActionPerformed

    /**
     * Método / Botón  para Insertar
     */
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String inputArista = this.InputArista.getText();
        newgrafo.Insert(inputArista);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Método para Mostrar
     */
    
    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        // TODO add your handling code here:
        this.ShowGrafo.setText(this.newgrafo.Imprimir());
    }//GEN-LAST:event_ShowActionPerformed

    /**
     * Método para Insertar un Vértice / Una Ciudad
     */
    
    private void InsertAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertAristaActionPerformed
        // TODO add your handling code here:
        String City1 = this.InsertarCity1.getText();
        String City2 = this.InsertarCity2.getText();
        int d = Integer.parseInt(this.Distance.getText());
        newgrafo.InsertArista(d, City1, City2);
    }//GEN-LAST:event_InsertAristaActionPerformed

    /**
     * Método para Eliminar una Arista / Dos Ciudades
     */
    
    private void DeleteAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAristaActionPerformed
        // TODO add your handling code here:
        String City1 = this.DeleteCity1.getText();
        String City2 = this.DeleteCity2.getText();
        newgrafo.DeleteArista(City1, City2);
    }//GEN-LAST:event_DeleteAristaActionPerformed

    /**
     * Método para Eliminar un Vértice / Una Ciudad
     */
    
    private void DeleteVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteVerticeActionPerformed
        // TODO add your handling code here:
        String element = this.InputDelete.getText();
        newgrafo.DeleteVertice(element);
    }//GEN-LAST:event_DeleteVerticeActionPerformed

    /**
     * Método para conocer la Distancia entre las Dos Ciudades
     */
    
    private void DistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanceActionPerformed

    /**
     * Método para Eliminar un Vértice
     */
    
    private void InputDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDeleteActionPerformed

    /**
     * Método para Ingresar una Primera Ciudad
     */
    
    private void DeleteCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteCity1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteArista;
    private javax.swing.JTextField DeleteCity1;
    private javax.swing.JTextField DeleteCity2;
    private javax.swing.JButton DeleteVertice;
    private javax.swing.JTextField Distance;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField InputArista;
    private javax.swing.JTextField InputDelete;
    private javax.swing.JButton InsertArista;
    private javax.swing.JTextField InsertarCity1;
    private javax.swing.JTextField InsertarCity2;
    private javax.swing.JButton Show;
    private javax.swing.JTextArea ShowGrafo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
